{{- if and .Values.istio.enabled .Values.istio.hardened.enabled .Values.istio.hardened.jaeger.enabled -}}
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: es-communication-jaeger
  namespace: {{ .Release.Namespace | quote }}
spec:
  selector:
    matchLabels:
      common.k8s.elastic.co/type: elasticsearch
  action: ALLOW
  rules:
  - from:
    - source:
        namespaces: {{ .Values.istio.hardened.jaeger.namespaces | toYaml | nindent 10 }}
        principals: {{ .Values.istio.hardened.jaeger.principals | toYaml | nindent 10 }}
    to:    
    - operation:
        ports: ["9200"]
{{- end }}
