{{- if and .Values.istio.enabled .Values.istio.hardened.enabled -}}
{{- range .Values.istio.kibana.gateways -}}
{{- $gatewayParts := split "/" . }}
{{- $namespace := $gatewayParts._0 }}
{{- $name := $gatewayParts._1 }}
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: "ek-{{ $name }}-ingressgateway-authz-policy-kibana"
  namespace: {{ $.Release.Namespace }}
spec:
  selector:
    matchLabels:
      kibana.k8s.elastic.co/name: logging-ek
  action: ALLOW
  rules:
  - from:
    - source:
        namespaces:
        - {{ $namespace }}
        principals:
        - "cluster.local/ns/{{ $namespace }}/sa/{{ $name }}-ingressgateway-service-account"
---
{{ end -}}
{{- end }}