apiVersion: v1
description: Elasticsearch stats exporter for Prometheus
name: prometheus-elasticsearch-exporter
version: 4.14.0
kubeVersion: ">=1.10.0-0"
appVersion: 1.5.0
home: https://github.com/prometheus-community/elasticsearch_exporter
sources:
  - https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-elasticsearch-exporter
keywords:
  - metrics
  - elasticsearch
  - monitoring
maintainers:
  - name: svenmueller
    email: sven.mueller@commercetools.com
  - name: desaintmartin
    email: cedric@desaintmartin.fr
  - name: gmiernicki
    url: https://repo1.dso.mil/gmiernicki
