{{- if and .Values.networkPolicies.enabled .Values.autoRollingUpgrade.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all-egress
  namespace: {{ .Release.Namespace }}
spec:
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        # ONLY Block requests to AWS metadata IP
        except:
        - 169.254.169.254/32
  podSelector: {}
  policyTypes:
  - Egress
{{- end }}