{{- if and .Values.istio.enabled .Values.istio.hardened.enabled .Values.istio.hardened.mattermost.enabled -}}
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: es-communication-mattermost
  namespace: {{ .Release.Namespace | quote }}
spec:
  selector:
    matchLabels:
      common.k8s.elastic.co/type: elasticsearch
  action: ALLOW
  rules:
  - from:
    - source:
        namespaces: {{ .Values.istio.hardened.mattermost.namespaces | toYaml | nindent 10 }}
        principals: {{ .Values.istio.hardened.mattermost.principals | toYaml | nindent 10 }}
    to:
    - operation:
        ports: ["9200"]
{{- end }}