apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.kibana.serviceAccountName | default "logging-kibana" }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.kibana.serviceAccountAnnotations }}
  annotations:
{{ toYaml .Values.kibana.serviceAccountAnnotations | indent 4 }}
  {{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.elasticsearch.serviceAccountName | default "logging-elasticsearch" }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.elasticsearch.serviceAccountAnnotations }}
  annotations:
{{ toYaml .Values.elasticsearch.serviceAccountAnnotations | indent 4 }}
  {{- end }}
