apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.kibana.serviceAccountName | default "logging-kibana" }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.elasticsearch.serviceAccountName | default "logging-elasticsearch" }}
  namespace: {{ .Release.Namespace }}
