{{- if include "elasticsearch.shouldDeployUpgradeResources" . }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-bb-upgrade
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed,before-hook-creation
    
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: bb-{{ .Release.Name }}-upgrade-view
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-bb-upgrade
  namespace: {{ .Release.Namespace }}
{{- end }}