{{- if and .Values.istio.enabled .Values.monitoring.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-elasticsearch-istio-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: elasticsearch-istio-metrics
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    common.k8s.elastic.co/type: elasticsearch
  ports:
    - name: istio-metrics
      port: 15020
      targetPort: 15020
      protocol: TCP
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-kibana-istio-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: kibana-istio-metrics
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    common.k8s.elastic.co/type: kibana
  ports:
    - name: istio-metrics
      port: 15020
      targetPort: 15020
      protocol: TCP
  clusterIP: None
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-elasticsearch-istio-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    prometheus: k8s
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: elasticsearch-istio-metrics
      app.kubernetes.io/instance: {{ .Release.Name }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: istio-metrics
      path: /stats/prometheus
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-kibana-istio-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    prometheus: k8s
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kibana-istio-metrics
      app.kubernetes.io/instance: {{ .Release.Name }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: istio-metrics
      path: /stats/prometheus
      interval: 30s
{{- end }}
