{{- if .Values.istio.enabled }}
apiVersion: "security.istio.io/v1beta1"
kind: PeerAuthentication
metadata:
  name: kibana-default
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      common.k8s.elastic.co/type: kibana
  mtls:
    mode: {{ .Values.istio.mtls.mode }}
{{- end }}
